[project]
site_name = "taxopy"
site_url = "https://apcamargo.github.io/taxopy"
repo_name = "apcamargo/taxopy"
repo_url = "https://github.com/apcamargo/taxopy"
nav = ["index.md", "guide.md", "reference.md"]
extra_css = ["stylesheets/extra.css"]
extra_javascript = ["js/mermaid.mjs"]

[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
permalink = "#"

[project.plugins.autorefs]
[project.plugins.search]

[project.plugins.mkdocstrings.handlers.python]
inventories = ["https://docs.python.org/3/objects.inv"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
inherited_members = true
modernize_annotations = true
separate_signature = true
show_root_heading = true
show_signature_annotations = true
show_source = true
show_symbol_type_heading = true
show_symbol_type_toc = true
signature_crossrefs = true

[project.theme]
language = "en"
features = [
  "content.code.annotate",
  "content.code.copy",
  "navigation.instant",
  "navigation.instant.prefetch",
  "navigation.instant.progress",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "toc.integrate"
]

[project.theme.font]
text = "Inter"
code = "JetBrains Mono"

[project.theme.icon]
logo = "lucide/tree-pine"
repo = "fontawesome/brands/github"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "yellow"
accent = "amber"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "yellow"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
